name: Elixir

on:
  push:
    branches:
      - master
      - develop
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-18.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp:
          - 22.x
          - 21.x
          - 20.x
          - 19.x
        elixir:
          - 1.3.x
          - 1.4.x
          - 1.5.x
          - 1.6.x
          - 1.7.x
          - 1.8.x
          - 1.9.x
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
